In [2]:
import numpy as np
import pandas
import matplotlib.pyplot as plt
%matplotlib notebook 
from scipy.integrate import solve_ivp 

**Solving Matrices**

## 5x5

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

## 6x6

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

## 7x7

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

## 8x8

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

## 9x9

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

## 10x10

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

## 11x11

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

## 12x12

In [ ]:
import numpy as np

A = np.matrix([[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
B = np.array([ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
C = np.linalg.solve(A, B)
print(C)

**Importing Matrices To be Solved**

In [ ]:
theta, mu = 0.1, 0.18
S = numpy.matrix(pandas.read_excel('matrixst1.xlsx'))
S1 = numpy.vstack([S,[0,1,0,0,0,0,0,0,0],[0,0,0,1,0,0,0,0,0]]) # Adding mu and zero GLY spec
B = np.array([0,0,0,0,0,0,theta,mu,0]).T
r= np.linalg.solve(S1, B)

# Editing an imported array
# print(a)
#  [[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]
    
#     print(np.delete(a, 1, 0))
#  [[ 0  1  2  3]
#  [ 8  9 10 11]]

# print(np.delete(a, 1, 1))
#  [[ 0  2  3]
#   [ 4  6  7]
#   [ 8 10 11]]
